---
- name: Install ntp
  package:
    name: "{{ ntp_packages }}"
    state: present

- name: Configure ntp
  template:
    src: "{{ ntp_configuration_file }}.j2"
    dest: /etc/{{ ntp_configuration_file }}
  notify:
    - restart ntp

- name: Install timezone information
  package:
    name: "{{ ntp_timezone_packages }}"
    state: present

- name: Configure timezone
  timezone:
    name: "{{ ntp_timezone }}"
  when:
    - ntp_timezone_supported | bool

- name: add line to crontab's root - backup
  cron:
    name: "backup openvz vps" 
    hour: "1" 
    minute: "30" 
    job: "/usr/sbin/ntpdate 0.north-america.pool.ntp.org > /dev/null"
    cron_file: "/etc/crontab"
    user: root
    
- name: Start and enable {{ ntp_service }}
  service:
    name: "{{ ntp_service }}"
    state: started
    enabled: yes