---
- name: Kibana
  hosts: all
  become: yes
  # gather_facts: yes
  roles:
    - { role: apt,  apt_packages: [ git, htop ]}
    - { role: kibana }
    - { role: monit }
    - { role: nginx }
    - { role: rsyslog, type: client }
    - { role: ini }
    - { role: ntp }   