---
- hosts: all

  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install required packages
      apt: rsyslog
      sudo: yes

    - name: Copy config rsyslog
      copy:
        src: ../files/rsyslog.conf
        dest: /etc/rsyslog.conf
        sudo: yes