---
  - name: Install and update required packages
    apt: 
      name: rsyslog
      update_cache: yes

  - name: Copy config rsyslog
    copy:
      src: ../files/rsyslog.conf
      dest: /etc/rsyslog.conf

  - name: Restarted rsyslog
    service:
      name: rsyslog
      state: restarted