---
- hosts: all
  tasks:
    - name: Update apt cache
      apt: update_cache
      sudo: yes

    - name: Install required packages
      apt: name={{ item }}
      sudo: yes
      with_items:
        - haproxy