---
- hosts: all

  tasks:
    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Install required packages
      apt: monit
      sudo: yes

    - name: Copy config monit
      copy:
        src: ../files/monitrc
        dest: /etc/monit
        sudo: yes