---
  - name: Install required packages
    apt: 
      name: monit
      update_cache: yes

  - name: Copy config monit
    copy:
      src: ../files/monitrc
      dest: /etc/monit/monitrc
      mode: 0600
      owner: root 
      group: root

  - name: restart monit
    service: 
      name: monit 
      state: restarted