- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - { role: apt,  apt_packages: [ git, htop, npm, python3-pip]}
    - { role: elastic }
    - { role: java }
    - { role: logstash }
    - { role: monit }
    - { role: ini }
    - { role: ntp }
    - { role: rsyslog }
  vars:
    elasticsearch_plugins:
    - name: elasticsearch/elasticsearch-discovery-ec2
    ansible_python_interpreter: /usr/bin/python3