apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: nginx
      image: 225050420367.dkr.ecr.us-west-2.amazonaws.com/task:nginxpy1
      ports:
        - containerPort: 80
    - name: app
      image: 225050420367.dkr.ecr.us-west-2.amazonaws.com/task:apppy