---
  - name: Install Elastic Deb Package
    become: yes
    apt:
      deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.13.4-amd64.deb
    
  - name: Create Logstash configuration files.
    template:
      src: elasticsearch.yml.j2
      dest: "/etc/elasticsearch/elasticsearch.yml"
      owner: root
      group: root
      mode: 0644
    notify: elasticsearch restart

  - name: elasticsearch-plugins | Install plugins
    elasticsearch_plugin:
      name: discovery-ec2
      src: https://artifacts.elastic.co/downloads/elasticsearch-plugins/discovery-ec2/discovery-ec2-7.13.4.zip
      state: present
      force: yes
    ignore_errors: yes
    notify: elasticsearch restart

  # - include: plugins.yaml 
  - include: docker.yaml

  # - name: Docker elasticsearch-head
  #   shell:
  #     cmd: docker run -d -p 192.168.32.10:9100:9100 mobz/elasticsearch-head:5

  # - name: Docker elasticsearch-HQ
  #   shell:
  #     cmd: docker run -d -p 192.168.32.10:5000:5000 elastichq/elasticsearch-hq
     
  - name: Start and Enabled ElasticSearch Service
    become: yes
    service:
      name: elasticsearch
      state: started
      enabled: yes
      