- name: elasticsearch-plugins | Install plugins
  command: "{{elasticsearch_home}}/bin/elasticsearch-plugin --install {{item.name}} creates={{elasticsearch_plugindir}}/{{item.dir|default(item.name.split('/')[-1])}}"
  with_items: "{{ elasticsearch_plugins }}"
  ignore_errors: yes
  notify: elasticsearch restart