  - name: Install Kibana Deb Package
    become: yes
    apt:
      deb: https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-amd64.deb
  
  - name: Update Kibana Config (Port)
    become: yes
    lineinfile:
      destfile: "{{ kibana_config }}"
      regexp: '#server.port: 5601'
      line: 'server.port: {{ kibana_port }}'

  - name: Update Kibana Config (IP Address)
    become: yes
    lineinfile:
      destfile: "{{ kibana_config }}"
      regexp: '#server.host'
      line: 'server.host: "{{ kibana_server }}"'

  - name: Update Kibana Config (Elasticsearch)
    become: yes
    lineinfile:
      destfile: "{{ kibana_config }}"
      regexp: '#elasticsearch.hosts: ["http://localhost:9200"]'
      line: 'elasticsearch.hosts: ["http://192.168.32.10:9200"]'
    
  - name: Start Kibana Service
    become: yes
    service:
      name: kibana
      state: started