---
  - name: Update apt cache
    apt: 
      update_cache: yes
      upgrade: yes
      cache_valid_time: "{{ apt_cache_valid_time }}"
      state: "{{ apt_state }}"
    become: true 

  - name: Install required packages
    apt: 
      name: "{{ apt_packages }}"
    become: true