  - name: Install Logstash Deb Package
    apt:
      deb: https://artifacts.elastic.co/downloads/logstash/logstash-7.13.4-amd64.deb

  - name: Create Logstash configuration files.
    template:
      src: "rsyslog.conf"
      dest: "/etc/logstash/conf.d/rsyslog.conf"
      owner: root
      group: root
      mode: 0644
    notify: restart logstash

  - name: Start Logstash Service
    service:
      name: logstash
      state: started
      enabled: yes