---
  - name: Install app
    apt:
      name: "nginx"
      state: latest

  - name: Config Nginx
    template:
      src: kibana.conf.j2
      dest: /etc/nginx/conf.d/kibana.conf
      mode: 0644
      owner: root 
      group: root
    notify: restart nginx

  - name: Start app
    service:
      name: "nginx"
      state: started