---
  - name: Installs haproxy load balancer
    apt: 
      name: haproxy 
      state: latest
      update_cache: yes


  - name: Pushes configuration
    template: 
      src: haproxy.cfg.j2 
      dest: /etc/haproxy/haproxy.cfg
      mode: 0644
      owner: root 
      group: root
    notify: restart haproxy

  - name: Started haproxy
    service: 
      name: haproxy 
      state: started    
  # - name: restart haproxy
  #   service: 
  #     name: haproxy 
  #     state: restarted