---
  - name: Installs haproxy load balancer
    apt: 
      name: haproxy 
      state: installed 
      update_cache: yes

  - name: Pushes configuration
    copy: 
      src: files/haproxy.cfg 
      dest: /etc/haproxy/haproxy.cfg 
      mode: 0640 
      owner: root 
      group: root
    notify:
      - restart haproxy

  - name: restart haproxy
    service: 
      name: haproxy 
      state: restarted