---
  - name: Install required packages
    apt: 
      name: monit
      update_cache: yes

  - name: Monit | Update the monit configuration (/etc/monit/monitrc)
    template:
      src: "monitrc.j2"
      dest: "/etc/monit/monitrc"
    notify:
      - restart monit