version: "3.9"
    
services:
  db:
    image: mysql:5.7
    # command: touch /var/log/mysql/general.log
    # command: mysqld --general-log=TRUE --general-log-file=/var/log/mysql/general-log.log
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
    volumes:
      - db_data:/var/lib/mysql
      - ./config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./log/mysql/error:/var/log/mysql
      # - ./log/mysql/general:/var/lib/mysql
    restart: always
    env_file:
      .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.2-php7.4-apache
    volumes:
      - wordpress_data:/var/www/html
      - ./log/apache:/var/log/apache2
    # ports:
    #   - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress #/run/secrets/wordpress-pass
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - wordpress-pass

  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx
    volumes: 
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ./data/nginx/cache:/var/lib/nginx/proxy_cache
    links:
      - wordpress
    ports:
      - 8989:8989
secrets:
  wordpress-pass:
    file: ./docker-secrets/wordpress-pass.txt
volumes:
  db_data: {}
  wordpress_data: {}

